[package]
name = "gen"
version = "0.1.0"
authors = ["徐志强 <652732310@qq.com>"]
edition = "2018"

[dependencies]
tera = {git = "https://github.com/Keats/tera", rev = "3409b1a"}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"